services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: scheduler
    ports:
      - "3306:3306"
